---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")

```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
library(tidyverse)
library(here)
```
```{r}
heartrate <- read_csv(here("data", "heartrate.csv"))
heartrate <- heartrate %>% 
  pivot_longer(-patient, names_to = "drug", values_to = "rate" )
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
# can technically do this without pivoting but needed for boxplot
heartrate %>% 
  filter(drug == "a") %>% 
  ggplot(aes(x=patient, y=rate))+
  geom_col()+
  labs(title = "Heartrate For Drug a", x = "Patients", y="Heartrate")+ # can use x=NULL to remove title
  theme(plot.title = element_text(hjust = 0.5))
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate %>% 
  ggplot(aes(x=drug,y=rate, fill=drug))+
  geom_boxplot(alpha=0.7)+ # transparency of color
  labs(title = "Heartrate Ranges for Drugs a-d", x = "Drug", y="Heartrate")+
  theme(plot.title = element_text(hjust = 0.5))
```

